app/helpers/logo_images_helper.rb, spec/helpers/logo_images_helper_spec.rb
Doesn't solve all the potential problems from 1082, but makes it hard to include an inexistent logo image via code.
=> Validate logo image size before including. refs #1082

app/mailers/devise_mailer.rb, config/initializers/devise.rb, spec/features/devise/confirmation_instructions_spec.rb, spec/features/devise/reset_password_instructions_spec.rb
The subject from devise emails was modified to match with the rest of the site emails.
refs #1421
=> Feature #1421 Subject on emails sent by devise are not like the others

app/controllers/users_controller.rb, app/views/users/new.html.haml, spec/controllers/users_controller_spec.rb, spec/features/users/new_user_spec.rb
Added flags "approved" (just when "require registration approval" is required by the site) and "allow to record" in the user registration form used by admins.
refs #1466
=> Feature #1466 - Add flags "approved" and "allow to record" in the user registration form

config/initializers/devise.rb, spec/features/devise/confirmation_instructions_spec.rb, spec/features/visitor_logs_in_spec.rb
Activating this option, devise will have the same behave regardless if the email provided exists in database or not.
refs #871
=> Bug #871 - Use default error message 'Forgot password' screen form

app/controllers/users_controller.rb, app/helpers/icons_helper.rb, app/models/abilities/member_ability.rb, app/views/manage/_destroy_user.html.haml, app/views/manage/_disabled_user.html.haml, app/views/manage/_enabled_user.html.haml, app/views/users/edit.html.haml, config/locales/en/mconf.yml, config/locales/pt-br/mconf.yml, config/routes.rb, spec/controllers/users_controller_spec.rb, spec/features/manage/admin_manages_users_spec.rb, spec/models/user_spec.rb
The destroy method previously used to disable users in the system was moved to a new method called disable. Now the destroy method is used to fully remove an user from the system.
Changed the delete icon from 'icon-remove-sign' to 'icon-trash'.
Created tests for destroy method.
refs #1153
=> Feature1153 - Allow admins to permanently remove users and spaces

app/controllers/users_controller.rb, app/mailers/user_mailer.rb, app/mailers/views/user_mailer/registration_by_admin_notification_email.haml, app/models/user.rb, app/workers/user_notifications_worker.rb, app/workers/user_registered_by_admin_sender_worker.rb, config/locales/en/_mailer.yml, config/locales/pt-br/_mailer.yml, spec/controllers/users_controller_spec.rb, spec/mailers/user_mailer_spec.rb, spec/workers/user_notifications_worker_spec.rb, spec/workers/user_registered_by_admin_sender_worker_spec.rb
Removed the unnecessary emails when a user is registered by an admin. Now when an admin register a new user, he will receive just one email announcing his new account.
refs #1469
=> Bug #1469 - Unnecessary emails when a user is registered by an admin and the flag "require admin approval" is set

app/models/user.rb, spec/models/user_spec.rb
That way, it behaves exactly as if the user had been disabled: his posts still show
a link to his profile, which results in a 404 when clicked.
refs #1511
=> Remove destroy dependency from User to Post

app/assets/javascripts/app/custom_bigbluebutton_rooms/_invitation_form.js.coffee, app/views/custom_bigbluebutton_rooms/_invitation_form.html.haml
Fixed the form to invite people to a conference, now the right component is focused.
refs #1547
=> Bug #1547 - Form to invite people to a conference doesn't focus the right component and generates error

app/workers/join_requests_worker.rb, db/migrate/20150416210956_recent_activity_remove_owner_from_space_join_options.rb, db/schema.rb, spec/workers/join_requests_worker_spec.rb
Fix to don't let workers break if the owner is not a "JoinRequest".
Migration to fix recent activities with wrong owners.
refs #1546
=> Bug #1546 - Error when a recent activity for a join request has an unexpected owner

app/assets/stylesheets/app/application/base.css.scss, app/models/abilities/member_ability.rb, app/models/abilities/superuser_ability.rb, app/views/spaces/_sidebar.html.haml, app/views/users/_detailed_user.html.haml, config/locales/en/mconf.yml, config/locales/pt-br/mconf.yml, spec/models/permission_spec.rb, spec/models/space_spec.rb
Changed the Abilities so that both global and space admins are now able to
remove users.
A user will not be able for removal if it's the last admin of that space.
=> Feature 1552 - Allow admins to remove users from spaces

app/assets/javascripts/app/join_requests/create_no_accept.js.coffee, app/controllers/join_requests_controller.rb, app/mailers/space_mailer.rb, app/mailers/views/space_mailer/join_no_accept_email.html.haml, app/models/join_request.rb, app/views/join_requests/create_no_accept.html.haml, app/views/public_activity/_join_request.html.haml, app/views/spaces/_admin_tabs.html.haml, app/workers/join_request_no_accept_sender_worker.rb, app/workers/join_requests_worker.rb, config/locales/en/_mailer.yml, config/locales/en/mconf.yml, config/locales/pt-br/_mailer.yml, config/locales/pt-br/mconf.yml, config/routes.rb
Add functionality so that Global Admins can add users to the spaces.
Deals with cases where there already was a pending Join Request from the user
being added on the space he's being added to.
This new mode of adding users to spaces was called a Join Request "no_accept",
since the user doesn't have to accept it, he's just added to the space. Maybe
the name is not the best, but I didn't want to call it "force_add" or something like that.
=> 1604: Allow global admins to add users to a space without the user having to accept it

app/views/my/edit_room.html.haml
This complements what has been made in mconf/bigbluebutton_rails#24
=> Feature1571 - Show layout names instead of keys

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
Modifications to let admins create conferences in any room and be moderator in any room who they join.
refs #1513
=> Feature #1513 - Admins should always be moderators in all web conference rooms

app/controllers/application_controller.rb, spec/controllers/custom_bigbluebutton_rooms_controller_spec.rb, spec/controllers/manage_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/features/users/edit_user_account_spec.rb
Any xhr request that is not from /manage/users or /manage/spaces, is a ignored path.
That correct the bug when you access a modal, via xhr, close it, and then access any page that will redirect back.
refs #1719
Both paths /bigbluebutton/rooms/:user/join ans /bigbluebutton/rooms/:user:end can not be redirectable
In application contrroler was added the regex for the both paths and changed the test for ignored paths from "include?" to "match", for each path.
refs #1721
=> Bugs1719 1721

app/controllers/shibboleth_controller.rb, lib/mconf/shibboleth.rb, spec/controllers/shibboleth_controller_spec.rb, spec/lib/mconf/shibboleth_spec.rb
Save the data returned by the federation into `ShibToken#data` after every successful sign in. Won't save if it is blank or empty.
So now checking the data in the session or checking the data in `ShibToken#data` should be the same when a user is signed in via Shibboleth.
refs #1778
=> Update the data in shib tokens after every valid sign in

app/controllers/space_events_controller.rb, app/models/abilities/base_ability.rb, app/models/abilities/member_ability.rb, app/models/space.rb, app/views/spaces/_menu.html.haml, app/views/spaces/_sidebar.html.haml, spec/controllers/space_events_controller_spec.rb, spec/models/bigbluebutton_room_spec.rb, spec/models/space_spec.rb
To not authorize the access to events/index it was needed create a new tah :index_events and block in the index with authorize!.
refs #1795
=> Page events/index is not anymore avaliable in unapproved spaces

app/views/layouts/_spaces_page_title.html.haml, app/views/space_events/_sidebar_events_simple.html.haml, app/views/spaces/_unified_space.html.haml, app/views/spaces/index.html.haml, app/views/users/_detailed_user.html.haml
Correct places where html tags in user input would be rendered into the page. 
Conflicts:
app/views/users/_detailed_user.html.haml
=> Remove unescaped HTML in user inputs

app/mailers/views/space_mailer/invitation_email.html.haml, config/locales/de/_mailer.yml, config/locales/en/_mailer.yml, config/locales/pt-br/_mailer.yml
Fixed bug #1776: Invitation to a private space shouldn't send the link to the space.
=> Invitation to a private space shouldn't send the link to the space.

app/controllers/events_controller.rb, app/models/abilities/member_ability.rb, app/models/event.rb, app/views/space_events/index.html.haml, config/locales/en/_events.yml, config/locales/pt-br/_events.yml, config/routes.rb, spec/controllers/events_controller_spec.rb, spec/models/user_spec.rb
Also block non-approved and disabled spaces from being able to create events like this.
Added some tests and extra corrections for problems that could arise with the events(new|create) methods and all the variation with their parameters.
=> Bug1928 -  prevent events/new from being accessible to users not in a space

app/controllers/shibboleth_controller.rb, app/models/ldap_token.rb, lib/mconf/ldap.rb, lib/mconf/shibboleth.rb, spec/controllers/shibboleth_controller_spec.rb, spec/factories/ldap_token.rb, spec/lib/mconf/shibboleth_spec.rb
A few thinks here:
* Don't store all the shibboleth env variables in the session cookie, just a flag denoting the user has logged in via shibboleth after the whole process is done
* Store extra DB information for LDAP users. This is here so that in users#edit we can show similar results for LDAP and Shib in the future.
Some tests dont make sense now that we don't store as much information in the session cookie, in the future we should think about rewriting or removing them.
=> Bug1895 -  Cookie overflow after signing in via Shibboleth

app/assets/javascripts/app/application/uploader.js.coffee, app/controllers/profiles_controller.rb, app/controllers/spaces_controller.rb, app/views/profiles/edit.html.haml, app/views/spaces/edit.html.haml
This way of doing things only shows valid upload types and makes things look relatively good in Chrome and Firefox
Also correct a line in upload_logo which would cause an error if the uploader failed to update the model (not a big deal :)
Solves bugs #501 and #353.
=> Explicit file type accepts in upload forms

app/controllers/my_controller.rb, spec/features/site/flag_require_registration_approval_spec.rb
added the referer link of the pagethe user is redirected to after first register fails
added tests to verify that this behaviour is now leading to the pending approval page
resolves #868
=> Send user to pending approval page if he registers after failing the first registration attempt

app/controllers/my_controller.rb, spec/features/site/flag_require_registration_approval_spec.rb
we are now using the shibboleth login flag which resolves the problem, detects that the user is coming from Shibboleth login and should see the pending page.
also changed the spec test to ensure the user left the page (which happens when using federation login) and then came back, now it catches the bug described in #877 
resolves #877
=> Changed pending page redirect verification

app/controllers/application_controller.rb
Added the stack trace of error 500 and error 404 (because some exception are being handled as 404)
Now when an exception occurs in production the first 10 lines of the stack trace will be added to production.log
Resolves #818
=> Added stack trace of exceptions to production log

lib/mconf/highlighter.rb, spec/lib/mconf/highlighter_spec.rb
Fixed the mutliple match issue and fixed escaping of regex, now users can search for "("
and other special characters from regexp properly.
Added spec tests for repetition of words in search bar and for the new index crop function
Resolves #901
=> Fixed highlighting multiple words search and RegEx escaping.

app/models/user.rb, spec/controllers/manage_controller_spec.rb
The search in manage/users now orders by ammount of matches before name.
Added spec to test that the manager will get the users ordered by amount of search matches.
Now if there is no search terms users are ordered by name. 
If there are search terms they are ordered by amount of matches and users with the same amount of matches are then ordered by name.
Resolves #890
=> Prioritize matches search by terms #890

app/controllers/sites_controller.rb, app/mailers/application_mailer.rb, app/models/site.rb, app/views/sites/edit.html.haml, app/views/sites/show.html.haml, config/locales/en/mconf.yml, config/locales/pt-br/mconf.yml, db/migrate/20161108173649_add_smtp_receiver_to_sites.rb, db/schema.rb, spec/mailers/application_mailer_spec.rb
Added a smtp_receiver e-mail to get the user feedback
Email is configurable in /site and will use smtp_sender if left blank
Resolves #894
=> Separate site reply email #894

app/models/space.rb, app/views/layouts/_spaces_page_title.html.haml, app/views/manage/_disabled_space.html.haml, app/views/manage/_enabled_space.html.haml, spec/features/manage/admin_manages_spaces_spec.rb
Now there will always be a button to approve spaces even if the Site does not require space approval
Every other view will show warnings about the "not approved" state of the space, consistently with the approved flag
Resolves #879 
The comment about Mconf-RNP similar scenario will be validated once this implementation is merged to the RNP fork.
=> Implemented the first suggested Solution

app/assets/stylesheets/app/application/font-awesome.css.scss, app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/helpers/icons_helper.rb, app/views/manage/_enabled_user.html.haml, app/views/users/edit.html.haml, config/locales/en/mconf.yml, config/locales/pt-br/mconf.yml, spec/features/manage/admin_manages_users_spec.rb
Now there will be an icon for the users on manage/user so that the admin can give and remove permission to record.
The icon will be red when the user already can record and grey when he can't, the tooltip will inform of the status of this user and clicking the button will switch it.
Resolves #918
=> Recording permission button user manage #918

app/models/space.rb, app/models/user.rb, config/initializers/acts_as_taggable_on.rb, config/initializers/bigbluebutton_rails.rb, spec/controllers/manage_controller_spec.rb
Fixed an issue where having a blank space in the beginning of search_by_terms params would generate a bad query, which would return all the registers of the table.
Now blanks are removed and will not be part of the query.
Resolves #924
=> Removing blanks from the search_by_terms param

app/assets/stylesheets/app/custom_bigbluebutton_rooms/invite_userid.css.scss, app/controllers/custom_bigbluebutton_rooms_controller.rb, app/controllers/sites_controller.rb, app/views/custom_bigbluebutton_rooms/invite_userid.html.haml, app/views/sites/edit.html.haml, app/views/sites/show.html.haml, config/locales/en/_simple_form.yml, config/locales/en/mconf.yml, config/locales/pt-br/_simple_form.yml, config/locales/pt-br/mconf.yml, db/migrate/20170119195523_add_unauth_access_to_conferences_to_site.rb, db/schema.rb, spec/controllers/custom_bigbluebutton_rooms_controller_spec.rb
Added the flag.
Unauthorized users can't login and join + join_mobile will not join if no user is logged and the flag is set false.
This flag ENABLES login without authentication, thus TRUE means guests can login.
Resolves #927
=> Guest login flag #927

app/assets/javascripts/app/application/base.js.coffee, app/assets/javascripts/app/custom_bigbluebutton_rooms/user_edit.js.coffee, app/assets/javascripts/app/my/_all.js.coffee, app/assets/javascripts/app/spaces/_sidebar.js.coffee, app/assets/javascripts/app/spaces/webconference.js.coffee, app/models/profile.rb, app/models/space.rb, app/models/user.rb, app/views/custom_bigbluebutton_rooms/user_edit.html.haml, config/locales/en/_simple_form.yml, config/locales/pt-br/_simple_form.yml, lib/tasks/db/populate.rake, spec/models/profile_spec.rb, spec/models/user_spec.rb
- Users can now edit their webconference room name and URL
- Users can also edit the name and URL of their spaces webconference rooms,
if they match the required abilities/permissions
- The name of the webconference room will still be updated when the user fullname
(profile) is updated, but only if the room name and user full name are currently the same
- The URL is no longer going to update when a user's username (user) is updated,
since a user currently can't change his username, therefore, URLs will be generated once
when a user creates his account and then only updated by user input
- Space URL can be updated and follows the same behavior
- There is no flag to enable editing name and url, it will be a default behavior
Resolves #363 and #934
=> Allow users to change name and url of webconference rooms

app/controllers/sites_controller.rb, app/views/sites/edit.html.haml
The code for events was not removed, the flag will not be available
until events module is upgraded and serves a clearer/better function
=> Removed enable_events flag

config/workers_schedule.yml, db/migrate/20170531162723_bigbluebutton_rails_to220b.rb, db/schema.rb
will add a list of attendees and finish time info for meetings on servers with getStats api call
resolves #619
=> Adding tables and scheduling worker for new get_stats implementation

.env.development, .env.test, Gemfile, Gemfile.lock, app/assets/stylesheets/app/application/base.scss, app/assets/stylesheets/app/application/font-awesome.scss, app/assets/stylesheets/app/frontpage/show.scss, app/assets/stylesheets/app/registrations/new.scss, app/controllers/callbacks_controller.rb, app/helpers/icons_helper.rb, app/models/site.rb, app/models/user.rb, app/views/devise/shared/_social_login.html.haml, app/views/frontpage/show.html.haml, app/views/registrations/_signup_form.html.haml, app/views/registrations/new.html.haml, app/views/sessions/new.html.haml, config/application.rb, config/initializers/devise.rb, config/locales/en/mconf.yml, config/locales/pt-br/mconf.yml, config/routes.rb, lib/mconf/redirect_controller_module.rb, spec/features/site/flag_local_auth_enabled_spec.rb, spec/routing/callbacks_routing_spec.rb, spec/spec_helper.rb
Adding Facebook and Google authentication Login to Mconf login
=> Master social login

app/models/user.rb, spec/models/user_spec.rb
This will make users who are created by "Omniauth" social login be also confirmed (without e-mail notification).
=> Auto confirm social register
