- config/initializers/secret_token.rb
- config/initializers/session_store.rb
- lib/tasks/secret.rake
Assigned in 60 minutes the expiration time to the session cookie. Created the secret_key_base, refactored the secret.rake task to attach new secure tokens (secret_token, secret_key_base, pepper, secret_key).
refs #521 #1214
> Feature #521 - Expire sessions

- Gemfile.lock
- app/models/invitation.rb
- app/views/layouts/_chat.html.haml
- app/views/mweb_events/events/_title.html.haml
- app/views/mweb_events/participants/_guest_participant.html.haml
- app/views/private_messages/show.html.haml
- lib/tasks/db/populate.rake
Escape some javascript and html vulnerabilities and add bogus data to populate in the hopes of triggering new known vulnerabilities on development stage.
> Security fixes

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
Revised the roles to let superusers join any room as an attendee. If the room was not running the superuser can create the room and enter as a moderator.
refs #1472
> Bug #1472 - Permission error when a superuser tries to join a room in a private space

- Gemfile.lock
- db/migrate/20150226192217_bigbluebutton_rails_to200_f.rb
- db/schema.rb
> Add migration to create BigbluebuttonServerConfigs table

- app/controllers/custom_bigbluebutton_recordings_controller.rb
- app/helpers/custom_bigbluebutton_playback_types_helper.rb
- app/views/shared/_recording_playback.html.haml
- config/locales/en/_bigbluebutton_rails.yml
- config/locales/pt-br/_bigbluebutton_rails.yml
- spec/helpers/custom_bigbluebutton_playback_types_spec.rb
Improved the options to playback/download recordings and forcing the download recording to be downloaded by the browser with a suitable name.
refs #1482
> Feature1482 - Improve the options to playback/download recordings

- app/models/user.rb
- spec/models/user_spec.rb
Also, tests to ensure it's working.
refs #1512
> Add hook to disable space with no admin on user destroy

- app/controllers/feedback_controller.rb
- spec/controllers/feedback_controller_spec.rb
Solution was simple: add a before_filter hook to authenticate, except when we're coming
from a webconf.
Updated tests.
> Feature1554

- app/controllers/sites_controller.rb
- app/mailers/views/web_conference_mailer/invitation_email.html.haml
- app/models/space.rb
- app/models/user.rb
- app/views/my/edit_room.html.haml
- app/views/sites/edit.html.haml
- app/views/sites/show.html.haml
- app/views/spaces/webconference_options.html.haml
- config/locales/en/_bigbluebutton_rails.yml
- config/locales/en/_simple_form.yml
- config/locales/en/mconf.yml
- config/locales/pt-br/_bigbluebutton_rails.yml
- config/locales/pt-br/_mailer.yml
- config/locales/pt-br/_simple_form.yml
- config/locales/pt-br/mconf.yml
- db/migrate/20150417192747_add_room_dial_number_pattern_to_site.rb
- db/schema.rb
- lib/mconf/generate_dial_number.rb
- spec/lib/mconf/generate_dial_number_spec.rb
- spec/mailers/web_conference_mailer_spec.rb
- spec/models/space_spec.rb
- spec/models/user_spec.rb
> Add option to automatically generate dial numbers

- .travis.yml
- Gemfile
- Gemfile.lock
- app/workers/base_worker.rb
- app/workers/invitation_sender_worker.rb
- app/workers/invitations_worker.rb
- app/workers/join_request_invite_sender_worker.rb
- app/workers/join_request_sender_worker.rb
- app/workers/join_requests_worker.rb
- app/workers/participant_confirmations_sender_worker.rb
- app/workers/participant_confirmations_worker.rb
- app/workers/private_messages_worker.rb
- app/workers/processed_join_request_sender_worker.rb
- app/workers/user_approved_sender_worker.rb
- app/workers/user_needs_approval_sender_worker.rb
- app/workers/user_notifications_worker.rb
- app/workers/user_registered_by_admin_sender_worker.rb
- app/workers/user_registered_sender_worker.rb
- config/initializers/resque_mailer.rb
- spec/workers/invitation_sender_worker_spec.rb
- spec/workers/join_request_invite_sender_worker_spec.rb
- spec/workers/join_request_sender_worker_spec.rb
- spec/workers/processed_join_request_sender_worker_spec.rb
- spec/workers/user_approved_sender_worker_spec.rb
- spec/workers/user_needs_approval_sender_worker_spec.rb
- spec/workers/user_registered_by_admin_sender_worker_spec.rb
- spec/workers/user_registered_sender_worker_spec.rb
When using  multiple workers workers or just being unlucky with the timing on slow tasks.
> 1480 - Several fixes to ensure Resque doesnt re-run tasks

- Gemfile
- Gemfile.lock
- README.rdoc
- app/assets/javascripts/app/application/notifications.js.coffee
- app/controllers/confirmations_controller.rb
- app/controllers/passwords_controller.rb
- app/controllers/shibboleth_controller.rb
- app/controllers/users_controller.rb
- app/views/layouts/_notifications.html.haml
- spec/factories/user.rb
- spec/features/devise/confirmation_email_spec.rb
- spec/features/users/edit_user_account_spec.rb
Compare this branch ( https://hakiri.io/projects/44a7c47e2ec5a9/stacks/0901d019284fb6 ) with master ( https://hakiri.io/projects/44a7c47e2ec5a9/stacks/2d82be9b4ba454 )
> New security fixes (update rails4 and other libs)

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- config/environments/production.rb
Modifications made to start using elasticsearch to process informations about mconf-web.
> Adding lograge to convert logs to logstash format.

- app/controllers/custom_bigbluebutton_rooms_controller.rb
- app/helpers/users_helper.rb
- app/views/custom_bigbluebutton_rooms/_invitation_form.html.haml
- config/locales/en/mconf.yml
- config/locales/es-419/mconf.yml
- config/locales/pt-br/mconf.yml
- lib/mconf/timezone.rb
- spec/controllers/custom_bigbluebutton_rooms_controller_spec.rb
- spec/lib/mconf/timezone.rb
With several tests and some UI improvements
> Bug1709 - Observe daylight savings time when converting timezones

- app/controllers/join_requests_controller.rb
- spec/controllers/join_requests_controller_spec.rb
+ some refactorings on the join requests controller
refs #1681
> User can't join request a space they already belong

- app/controllers/users_controller.rb
- spec/controllers/users_controller_spec.rb
> Now users can not edit attributes they shouldn't be able

- Gemfile
- Gemfile.lock
- app/views/users/edit.html.haml
- lib/mconf/timezone.rb
- spec/lib/mconf/timezone.rb
> Correct GMT offset when DST is in effect is displayed.

- app/controllers/custom_bigbluebutton_recordings_controller.rb
- spec/controllers/custom_bigbluebutton_recordings_controller_spec.rb
> Playback of recordings in public spaces is now open to anonnymous users

- app/assets/javascripts/app/attachments/index.js.coffee
> In attachments view, dont activate uploader if other modals are shown

- app/controllers/shibboleth_controller.rb
- spec/controllers/shibboleth_controller_spec.rb
> Fix error associating an old shibboleth account to a new shibboleth account

- app/controllers/my_controller.rb
- app/mailers/devise_mailer.rb
- app/models/abilities/member_ability.rb
- app/models/ldap_token.rb
- app/models/user.rb
- db/migrate/20151020182042_add_new_account_to_ldap_token.rb
- db/schema.rb
- lib/devise/overrides.rb
- lib/mconf/ldap.rb
- lib/tasks/ldap.rake
- spec/features/ldap/disabled_ldap_features_spec.rb
- spec/features/ldap/misconfiguration_spec.rb
- spec/features/ldap/user_signs_in_spec.rb
- spec/features/shibboleth/disabled_shibboleth_features_spec.rb
- spec/features/shibboleth/user_signs_in_spec.rb
- spec/lib/mconf/ldap_spec.rb
- spec/models/user_spec.rb
- spec/support/feature_helpers.rb
- spec/support/mconf_ldap_server.rb
Still missing ldap integration tests
> Feature1155 -  Don't allow users logged via Shibboleth or LDAP to login via local authentication

- app/controllers/manage_controller.rb
- app/controllers/users_controller.rb
- app/helpers/users_helper.rb
- app/models/recent_activity.rb
- app/models/user.rb
- app/views/join_requests/_request.html.haml
- app/views/mweb_events/participants/_guest_participant.html.haml
- app/views/mweb_events/participants/_participant.html.haml
- app/views/spaces/user_permissions.html.haml
- app/views/users/_detailed_user.html.haml
- app/views/users/_simple_user.html.haml
- app/views/users/select.rabl
- spec/controllers/users_controller_spec.rb
- spec/models/recent_activity_spec.rb
- spec/models/user_spec.rb
This ties up issues #1277 and #1447
> Dont show activity of private spaces on public user activity

- Gemfile
- spec/spec_helper.rb
Still need to add the repo_token to travis-ci interface
> Add code climate coverage

- app/assets/javascripts/app/my/_all.js.coffee
- app/assets/javascripts/app/spaces/_sidebar.js.coffee
- app/controllers/application_controller.rb
- app/controllers/custom_bigbluebutton_rooms_controller.rb
- app/controllers/sites_controller.rb
- app/models/abilities/base_ability.rb
- app/models/abilities/member_ability.rb
- app/views/custom_bigbluebutton_rooms/join_options.html.haml
- app/views/my/_webconference_room.html.haml
- app/views/sites/edit.html.haml
- app/views/sites/show.html.haml
- app/views/spaces/_sidebar_webconf_buttons.html.haml
- config/locales/de/_simple_form.yml
- config/locales/de/mconf.yml
- config/locales/en/_simple_form.yml
- config/locales/en/mconf.yml
- config/locales/es-419/_simple_form.yml
- config/locales/es-419/mconf.yml
- config/locales/pt-br/_simple_form.yml
- config/locales/pt-br/mconf.yml
- config/routes.rb
- db/migrate/20151210123701_remove_webconf_auto_record_from_sites.rb
- db/schema.rb
- lib/tasks/db/populate.rake
- spec/controllers/application_controller_spec.rb
- spec/controllers/custom_bigbluebutton_rooms_controller_spec.rb
- spec/models/bigbluebutton_room_spec.rb
- spec/routing/custom_bigbluebutton_rooms_spec.rb
- spec/support/helpers.rb
> Revert "Removed all references of 'webconf_auto_record' flag. refs #1801"

- Gemfile
- Gemfile.lock
- app/models/join_request.rb
- app/views/join_requests/_invitation.html.haml
- spec/controllers/attachments_controller_spec.rb
- spec/controllers/confirmations_controller_spec.rb
- spec/controllers/custom_bigbluebutton_rooms_controller_spec.rb
- spec/controllers/feedback_controller_spec.rb
- spec/controllers/join_requests_controller_spec.rb
- spec/controllers/mweb_events_events_controller_spec.rb
- spec/controllers/participant_confirmations_controller_spec.rb
- spec/controllers/permissions_controller_spec.rb
- spec/controllers/posts_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
- spec/controllers/session_locales_controller_spec.rb
- spec/controllers/shibboleth_controller_spec.rb
- spec/controllers/spaces_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/features/join_requests/accepting_users_in_a_space_spec.rb
- spec/models/join_request_spec.rb
- spec/models/space_spec.rb
- spec/models/user_spec.rb
- spec/spec_helper.rb
- spec/support/matchers/shoulda/should_authorize_macro.rb
- spec/support/shared_examples/spaces.rb
Addressing http://dev.mconf.org/redmine/issues/1873
Refactor join request a little, more validations for the model and more tests.
Bonus: updating shoulda-matchers to latest version and adapt old tests to it.
> Feature1873 - more tests and validations for join requests

- app/assets/javascripts/application.js
refs #1909
Should solve the problem pointed here http://dev.mconf.org/redmine/issues/1909
> Add extra momentjs locales for 'de' and 'es'

- lib/devise/strategies/ldap_authenticatable.rb
- spec/features/ldap/user_signs_in_spec.rb
- spec/support/ldap_server.rb
Description of the problem in Redmine: http://dev.mconf.org/redmine/issues/1882
> Bug1882 - Explicitly fail LDAP users which have not informed a password

- app/controllers/spaces_controller.rb
- app/controllers/users_controller.rb
- app/views/spaces/user_permissions.html.haml
- app/views/users/index.html.haml
- spec/controllers/spaces_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/features/spaces/space_admin_user_permissions_spec.rb
- spec/features/spaces/visiting_space_users_list_spec.rb
It was added some pending controller and view-features tests, also.
> Adding Feature #1802 - pagination into user lists and user permissions of spaces

- lib/mconf/approval_controller_module.rb
- spec/controllers/users_controller_spec.rb
> Activity for user.approved even if admin does it via user#edit

- app/controllers/events_controller.rb
- config/locales/en/_events.yml
- spec/controllers/events_controller_spec.rb
> redirection_path expanded when user is not logged in

- app/controllers/errors_controller.rb
> Prevent further errors if ErrorsController is executed without an exception

- app/views/manage/_disabled_space.html.haml
- app/views/manage/_disabled_user.html.haml
- app/views/manage/_enabled_space.html.haml
- app/views/manage/_enabled_user.html.haml
- lib/mconf/highlighter.rb
- spec/lib/mconf/highlighter_spec.rb
Made with love <3
For issue #549.
> Highlight with support for special characters

- app/assets/javascripts/app/application/resource_filter.js.coffee
- app/assets/stylesheets/app/manage/users.css.scss
- app/views/manage/_disabled_space.html.haml
- app/views/manage/_disabled_user.html.haml
- app/views/manage/_enabled_space.html.haml
- app/views/manage/_enabled_user.html.haml
- lib/mconf/highlighter.rb
- spec/lib/mconf/highlighter_spec.rb
corrected highligter function html escaping when adding tags to the user text
on users and spaces manage tabs
corrected the manage user and manage spaces view to show html escaping correctly
resolves #839
> Resolving issues with HTML entities when highlighting search on management page

- app/assets/stylesheets/app/manage/users.css.scss
- app/controllers/manage_controller.rb
- app/helpers/users_helper.rb
- app/models/ldap_token.rb
- app/models/shib_token.rb
- app/models/user.rb
- app/views/manage/_enabled_user.html.haml
- app/views/manage/users.html.haml
- config/locales/en/mconf.yml
- config/locales/pt-br/mconf.yml
- spec/controllers/manage_controller_spec.rb
- spec/features/manage/admin_manages_users_spec.rb
Added Last Login date and method to manage/users user list
Added Available login methods
Added Filters for Available Login Methods
Resolves #889
> Add signin data manage users

- app/models/space.rb
- config/initializers/bigbluebutton_rails.rb
- spec/controllers/manage_controller_spec.rb
Added search_by_terms matches prioritizer to /spaces, /manage/spaces and /manage/recordings
Created feature specs for expected behavior
This implements #890 for spaces and recordings.
> Prioritizer for search_by_terms on spaces and recordings

- app/controllers/application_controller.rb
- app/helpers/application_helper.rb
- config/locales/en/mconf.yml
- config/locales/pt-br/mconf.yml
- lib/mconf/allow_params_for_module.rb
- lib/mconf/bigbluebutton_rails_additions.rb
- lib/mconf/error_rendering_module.rb
- lib/mconf/lograge_additions.rb
Cleanup ApplicationController by moving complex methods to external modules and classes.
> Cleanup ApplicationController, move methods to external modules
